version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learning-nest-js
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules